import 


const createUser = async () => {
    try {
        
    } catch (error) {
        console.log('error', error)
    }
}